#tvae --name 'bubbles_starmen'
#tvae --name 'tvae_L0_starmen'
#tvae --name 'tvae_Lshort_starmen'
#tvae --name 'tvae_Lpartial_starmen'
#tvae --name 'tvae_Lhalf_starmen'
#tvae --name 'bubbles_starmen'

#tvae --name 'bubbles_colormnist'
#tvae --name 'tvae_L0_colormnist'
#tvae --name 'tvae_Lshort_colormnist'
#tvae --name 'tvae_Lpartial_colormnist'
#tvae --name 'tvae_Lhalf_colormnist'

#tvae --name 'bubbles_sprites'
#tvae --name 'tvae_L0_sprites'
#tvae --name 'tvae_Lshort_sprites'
#tvae --name 'tvae_Lpartial_sprites'
#tvae --name 'tvae_Lhalf_sprites'

#tvae --name 'bubbles_chairs'
#tvae --name 'tvae_L0_chairs'
#tvae --name 'tvae_Lshort_chairs'
#tvae --name 'tvae_Lpartial_chairs'
#tvae --name 'tvae_Lhalf_chairs'

tvae --name 'bubbles_rotmnist'
tvae --name 'tvae_L0_rotmnist'
tvae --name 'tvae_Lshort_rotmnist'
tvae --name 'tvae_Lpartial_rotmnist'
tvae --name 'tvae_Lhalf_rotmnist'